export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  ADJUSTER = 'ADJUSTER',
  ADMIN = 'ADMIN',
}

export enum ClaimStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  AI_PROCESSING = 'AI_PROCESSING',
  ADJUSTER_REVIEW = 'ADJUSTER_REVIEW',
  INVESTIGATION = 'INVESTIGATION',
  INFORMATION_REQUIRED = 'INFORMATION_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SETTLEMENT = 'SETTLEMENT',
  CLOSED = 'CLOSED',
}

export enum ClaimType {
  VEHICLE = 'VEHICLE',
  PROPERTY = 'PROPERTY',
  HEALTH = 'HEALTH',
  LIFE = 'LIFE',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum DocumentType {
  CLAIM_FORM = 'CLAIM_FORM',
  POLICE_REPORT = 'POLICE_REPORT',
  REPAIR_ESTIMATE = 'REPAIR_ESTIMATE',
  DAMAGE_PHOTO = 'DAMAGE_PHOTO',
  MEDICAL_BILL = 'MEDICAL_BILL',
  ID_PROOF = 'ID_PROOF',
  OTHER = 'OTHER',
}
