FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig.base.json ./
COPY packages/shared packages/shared
COPY apps/worker apps/worker
RUN npm install
RUN npm run build:shared
RUN npm run build:worker

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
COPY packages/shared/package*.json packages/shared/
COPY apps/worker/package*.json apps/worker/
RUN npm install --only=production
COPY --from=builder /app/packages/shared/dist packages/shared/dist
COPY --from=builder /app/apps/worker/dist apps/worker/dist
CMD ["npm", "run", "start", "--prefix", "apps/worker"]
